#theme: minima
theme: jekyll-theme-cayman

show_downloads: false

title: Shrestha Files
description: A Modern Dual Pane File Manager for Windows 10 and Windows 11 Devices

google_analytics: G-REJKSFYBN
