#theme: minima
theme: jekyll-theme-cayman

show_downloads: false

title: S Files Pro X (Shrestha Files)
description: A Modern Dual Pane File Manager with Tabs and Colorful Themes for Windows 11 and Windows 10 Devices

google_analytics: G-REJKSFYBN
